### ISSUE TITLE
Causes not compiled errors with ActiveAdmin

### ISSUE THREAD

**Issue by chrise86** [ndbroadbent/turbo-sprockets-rails3#7] opened 2012-10-05 12:44 UTC
After deploying with turbo sprockets ActiveAdmin started giving errors about files not being compiled.

i.e. active_admin.css, active_admin/print.css

**Comment by ndbroadbent** [comment] 2012-10-05 13:08
Hi there,

ActiveAdmin is working well for me in my own Rails app after deploying with turbo sprockets. Have you have added the following to `config/application.rb` (or `config/environments/production.rb`)?

``` ruby
config.assets.precompile += [
  'active_admin.js',
  'active_admin.css',
  'active_admin/print.css'
]
```

Please also have a look at the contents of `public/assets/manifest.yml` after compiling. If you see lines similar to: `!binary "YmcucG5n": be970f93cd2fba93cbef8e9fa4d29b1b`, then this could be the cause of your problem. This should be fixed if you update the gem to version `0.1.7`.

Thanks!

**Comment by jarthod** [comment] 2012-10-05 13:17
`activeadmin` (0.4.4) is also working fine for me with `turbo_sprockets_rails3` (0.1.5 & 0.1.7)
I didn't customized it, it's a brand new active admin setup with just a few models.

**Comment by ndbroadbent** [comment] 2012-10-05 13:23
Here's another likely cause for your problem:

> Warning: Don't add this gem to the `:assets` group. It must be available in the production environment, since it overrides the asset path helpers and changes the manifest format.

I've just added that note to the README, thanks to @jarthod for pointing it out :)

**Comment by chrise86** [comment] 2012-10-05 13:27
Hmm very strange, I even tried with using the gem straight from master, and I haven't put the gem in the assets group

**Comment by ndbroadbent** [comment] 2012-10-05 13:32
Is there a line for `active_admin.css` in your `public/assets/manifest.yml` file, under the `:digest_files` key?
Does `public/assets/active_admin.css` actually get compiled, or is it missing?

**Comment by ndbroadbent** [comment] 2012-10-06 10:02
Closing for now since I can't reproduce this

**Closed as completed by ndbroadbent** 2012-10-06 10:02 UTC
