### ISSUE TITLE
ActionView::Template::Error (application.css isn't precompiled): 

### ISSUE THREAD

**Issue by macmartine** [ndbroadbent/turbo-sprockets-rails3#14] opened 2012-10-10 22:34 UTC
I upgraded to 0.1.13 and now when I go to my app I get ActionView::Template::Error (application.css isn't precompiled): 

gem 'turbo-sprockets-rails3', '~> 0.1.13' is at the base of the Gemfile, and not in the :assets block.

**Comment by kirs** [comment] 2012-10-10 22:37
I have the same issue :(

**Comment by ndbroadbent** [comment] 2012-10-11 00:23
@macmartine - What version were you using before you upgraded?

**Comment by ndbroadbent** [comment] 2012-10-11 01:48
Sorry guys, I can't reproduce this. More information would be really helpful.

Please start your rails console in the production environment (`RAILS_ENV=production rails console`), and post the output of the following commands:

``` ruby
require 'pp'
pp Rails.application.config.assets; nil
pp Rails.application.assets.each_logical_path.to_a; nil
```

Thanks!

**Comment by macmartine** [comment] 2012-10-11 15:46
I was previously using whatever bundler was pulling down by default -- I just tried using this for the first time yesterday and had run into https://github.com/ndbroadbent/turbo-sprockets-rails3/issues/12

Here's the requested output:

```
1.9.1 :001 > require 'pp'
 => false 
1.9.1 :002 > pp Rails.application.config.assets; nil
{:enabled=>true,
 :paths=>
  ["/apps/eg/production/releases/20121010234627/app/assets/images",
   "/apps/eg/production/releases/20121010234627/app/assets/javascripts",
   "/apps/eg/production/releases/20121010234627/app/assets/stylesheets",
   "/apps/eg/production/releases/20121010234627/lib/assets/javascripts",
   "/apps/eg/production/releases/20121010234627/vendor/assets/images",
   "/apps/eg/production/releases/20121010234627/vendor/assets/javascripts",
   "/apps/eg/production/releases/20121010234627/vendor/assets/stylesheets",
   "/apps/eg/production/shared/bundle/ruby/1.9.1/gems/jquery-rails-2.1.3/vendor/assets/javascripts",
   "/apps/eg/production/shared/bundle/ruby/1.9.1/gems/saas-kit-2.5.2/app/assets/stylesheets",
   "/apps/eg/production/shared/bundle/ruby/1.9.1/gems/remotipart-1.0.2/vendor/assets/javascripts"],
 :precompile=>
  [#<Proc:0x00000003a4e770@/apps/eg/production/shared/bundle/ruby/1.9.1/gems/railties-3.2.7/lib/rails/application/configuration.rb:48>,
   /(?:\/|\\|\A)application\.(css|js)$/,
   "*.js",
   "controllers/*.js",
   "controllers/admin/*.js",
   "application.css",
   "users.css",
   "widget.css",
   "bootstrap_and_overrides.css",
   "customer_center.css",
   "jquery-ui-override.css",
   "mobile.css",
   "jquery-ui-1.8.18.custom.css",
   "jquery.colorpicker.css",
   "jquery.miniColors.css",
   "jquery.timePicker.css",
   "jquery.weekcalendar.css"],
 :prefix=>"/assets",
 :version=>"1.1",
 :debug=>false,
 :compile=>false,
 :digest=>true,
 :manifest=>nil,
 :cache_store=>
  [:file_store,
   "/apps/eg/production/releases/20121010234627/tmp/cache/assets/"],
 :js_compressor=>nil,
 :css_compressor=>nil,
 :initialize_on_precompile=>true,
 :logger=>nil,
 :compress=>true,
 :digests=>
  {"backgrounds/checkered.jpg"=>
    "backgrounds/checkered-88b3d8b55375101e1d8f81539e0c3645.jpg",
   "bio/mm.jpg"=>
    "bio/mm-1ca953911fa83896a8225d4d2833aa49.jpg",
   "evergreen-logo-medium.png"=>
    "evergreen-logo-medium-d02e26424c5fef56511166782ca3c965.png",
   "evergreen-logo.png"=>"evergreen-logo-db1907283315a3f57203af59f4088ee9.png",
   "icons/cvv.gif"=>"icons/cvv-3a4ed74ffc65c3637f19e69546210726.gif",
   "icons/envelope.png"=>"icons/envelope-eb332d0472585138f6393c2892ac359f.png",
   "icons/glyphicons-halflings-white.png"=>
    "icons/glyphicons-halflings-white-252e8593dee501cd4c5b7494e30ba515.png",
   "icons/glyphicons-halflings.png"=>
    "icons/glyphicons-halflings-d639e72c657ef6390b2c7095ae61ced8.png",
   "icons/gravatar.jpg"=>"icons/gravatar-98c18639a17a1596869c2ee5cfb67f90.jpg",
   "icons/phone.png"=>"icons/phone-583d79a32625602803e01b56a7dd5bd5.png",
   "icons/skype-icon.png"=>
    "icons/skype-icon-b676ca2f5cd49391b0acf46155cf5210.png",
   "icons/twitter-icon.png"=>
    "icons/twitter-icon-814b3f78232510beba9a441fa38ed4ec.png",
   "application.js"=>"application-f446610fd56cd1263e9dbc6ccff2b206.js",
   "application.mobile.js"=>
    "application.mobile-5f2e15ffb4078c4aa8483da0bc67010e.js",
   "controllers/admin/affiliates.js"=>
    "controllers/admin/affiliates-cd050a3742c60b211272b88f6ac0bd05.js",
   "controllers/admin/application.js"=>
    "controllers/admin/application-e0d5b801f926b15a238089d08fe2f930.js",
   "controllers/admin/appointments.js"=>
    "controllers/admin/appointments-49f3cf29dfc8343847c3081e94d726e7.js",
   "controllers/admin/businesses.js"=>
    "controllers/admin/businesses-9886c1fbd5631d569a6b5cb45e59a96c.js",
   "controllers/admin/calendar_settings_groups.js"=>
    "controllers/admin/calendar_settings_groups-db3b20db29b9b8ccd59e5db534ab8cd9.js",
   "controllers/admin/calendars.js"=>
    "controllers/admin/calendars-4e3d6fd9d5c7fe7df85d43ac02bf3f5a.js",
   "controllers/admin/calendars_main.js"=>
    "controllers/admin/calendars_main-988850b097f4e166b5cea6cdc4bc04fb.js",
   "controllers/admin/calendars_mini_cal.js"=>
    "controllers/admin/calendars_mini_cal-49884785115bd9db000a41d31bc43f54.js",
   "controllers/admin/clients.js"=>
    "controllers/admin/clients-27eaa53a56f5d31ea24aa5301302b133.js",
   "controllers/admin/dashboards.js"=>
    "controllers/admin/dashboards-59ee323156dd44eac4a5098c6454d716.js",
   "controllers/admin/locations.js"=>
    "controllers/admin/locations-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/notifications.js"=>
    "controllers/admin/notifications-ea9c29eeddce5cb11dc1d90d956561dc.js",
   "controllers/admin/payments.js"=>
    "controllers/admin/payments-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/personal_appointments.js"=>
    "controllers/admin/personal_appointments-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/promotes.js"=>
    "controllers/admin/promotes-42facbf65eb74800a8be686381205c30.js",
   "controllers/admin/providers.js"=>
    "controllers/admin/providers-e3aed021f3ad17297932d9d20acd6cc7.js",
   "controllers/admin/registrations.js"=>
    "controllers/admin/registrations-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/scheduling_settings_groups.js"=>
    "controllers/admin/scheduling_settings_groups-3e8477d1dc1a911dc872011e20b7b587.js",
   "controllers/admin/services.js"=>
    "controllers/admin/services-5f928d4ee6b6bd830e20946e5a0a1e64.js",
   "controllers/admin/setup_steps.js"=>
    "controllers/admin/setup_steps-cf77e010d86df0a398f3ed5c1aacda9f.js",
   "controllers/admin/statics.js"=>
    "controllers/admin/statics-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/styles_groups.js"=>
    "controllers/admin/styles_groups-074c8b6ca5ce585d0fcf4a3af2748309.js",
   "controllers/admin/users.js"=>
    "controllers/admin/users-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/admin/work_appointments.js"=>
    "controllers/admin/work_appointments-9844e9b85bbd49d4b82715256fa75eb0.js",
   "controllers/affiliates.js"=>
    "controllers/affiliates-cd050a3742c60b211272b88f6ac0bd05.js",
   "controllers/customer_center.js"=>
    "controllers/customer_center-44586b2404577610458641861b5ef2aa.js",
   "controllers/registrations.js"=>
    "controllers/registrations-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/sessions.js"=>
    "controllers/sessions-84b7c12ed451c12ff16b13b2a5636e87.js",
   "controllers/widget_appointments.js"=>
    "controllers/widget_appointments-79a79311177638f206ef62d532ffcd79.js",
   "customer_center.js"=>"customer_center-16e0ff9a72dddb34e25852138ae3bd88.js",
   "eg-widget.js"=>"eg-widget-886a240d721947d57b9f8e84ea19c4a1.js",
   "minisite.js"=>"minisite-2380cac625e2152cb3f11389492a8b60.js",
   "mobile.js"=>"mobile-b22d3c352d22e60493ca86870b1674fd.js",
   "safe.js"=>"safe-915f8831da25681cfe5200a4ef6e8f63.js",
   "setup_steps.js"=>"setup_steps-84b7c12ed451c12ff16b13b2a5636e87.js",
   "widget.js"=>"widget-c2a2eb4dbed5f4949221e0a3a288b7e8.js",
   "application.css"=>"application-d0289307d5b929a9277e8e28a13fb338.css",
   "bootstrap_and_overrides.css"=>
    "bootstrap_and_overrides-3574b2f67787920c9b1d98479f27a382.css",
   "customer_center.css"=>
    "customer_center-85439ecf8f1c6cf20a83c4fbc0580407.css",
   "jquery-ui-override.css"=>
    "jquery-ui-override-39cce6c9235c10a76fb11e774ad36b98.css",
   "mobile.css"=>"mobile-79f260ae4d1764c3c31e7a91baf6045f.css",
   "users.css"=>"users-51f74117e1172c720bffb0f70398e437.css",
   "widget.css"=>"widget-ced1f32724cce1565f36305657440156.css",
   "utils.js"=>"utils-1ef97e687a146dd33c1d90fe50d06241.js",
   "colors.png"=>"colors-2e9b22974e718253cb8d673b7204fcd6.png",
   "images/ui-bg_diagonals-thick_90_eeeeee_40x40.png"=>
    "images/ui-bg_diagonals-thick_90_eeeeee_40x40-f3f8e61d631c9d428c1b08d012b9a0fe.png",
   "images/ui-bg_flat_15_cd0a0a_40x100.png"=>
    "images/ui-bg_flat_15_cd0a0a_40x100-fd70a8b67c3d6198310ad96b2361ce91.png",
   "images/ui-bg_glass_100_e4f1fb_1x400.png"=>
    "images/ui-bg_glass_100_e4f1fb_1x400-cffc9a629c19090bc9b2411bd09e235e.png",
   "images/ui-bg_glass_50_3baae3_1x400.png"=>
    "images/ui-bg_glass_50_3baae3_1x400-995f097f4f5ba6126be167e52ae7f481.png",
   "images/ui-bg_glass_80_d7ebf9_1x400.png"=>
    "images/ui-bg_glass_80_d7ebf9_1x400-34053123782ba1180d2106f8798caaac.png",
   "images/ui-bg_highlight-hard_100_f2f5f7_1x100.png"=>
    "images/ui-bg_highlight-hard_100_f2f5f7_1x100-4a0e18b4ee2c3ffb38367e22296ba1f1.png",
   "images/ui-bg_highlight-hard_70_000000_1x100.png"=>
    "images/ui-bg_highlight-hard_70_000000_1x100-dec6c8ed731232a0cebca3df565727b0.png",
   "images/ui-bg_highlight-soft_100_deedf7_1x100.png"=>
    "images/ui-bg_highlight-soft_100_deedf7_1x100-8ee9feb6d936411a07fd92b67c531604.png",
   "images/ui-bg_highlight-soft_25_ffef8f_1x100.png"=>
    "images/ui-bg_highlight-soft_25_ffef8f_1x100-a28bd5f20e82c686c995392fca4e1fc0.png",
   "images/ui-icons_2694e8_256x240.png"=>
    "images/ui-icons_2694e8_256x240-08af0f4dba9ad4b76e6b4c990b750d47.png",
   "images/ui-icons_2e83ff_256x240.png"=>
    "images/ui-icons_2e83ff_256x240-280b0a61a8157112436f0dac58972d16.png",
   "images/ui-icons_3d80b3_256x240.png"=>
    "images/ui-icons_3d80b3_256x240-0ea43dfde1a9318137089c4ae93ed30e.png",
   "images/ui-icons_72a7cf_256x240.png"=>
    "images/ui-icons_72a7cf_256x240-b92b0b54de70faa3c2c0c2024492ea12.png",
   "images/ui-icons_ffffff_256x240.png"=>
    "images/ui-icons_ffffff_256x240-e40cd19ddddacd590819d60fceb52268.png",
   "trigger.png"=>"trigger-e4ee86fcc69c701ec5fdce85b28faeb6.png",
   "bootbox.min.js"=>"bootbox.min-0a9306f9be78e2d41daee1a74b2fae79.js",
   "bootstrap-dropdown.js"=>
    "bootstrap-dropdown-d229bf317e3fcc0a942927406e1963b9.js",
   "bootstrap-modal.js"=>"bootstrap-modal-60ea60dd02ba08078980b3c5c691c8a1.js",
   "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom.js"=>
    "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom-8708c0e8e5797e03d251827269996ded.js",
   "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom.min.js"=>
    "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom.min-72270beed32eb926e4e83a6b6f3212ca.js",
   "cdn/jquery/1.8.1/jquery-1.8.1.js"=>
    "cdn/jquery/1.8.1/jquery-1.8.1-cc821b37b2a1f0302d12d2570f45c693.js",
   "cdn/jquery/1.8.1/jquery-1.8.1.min.js"=>
    "cdn/jquery/1.8.1/jquery-1.8.1.min-fcae7687b696ae5f7bfe23659a7b0521.js",
   "cdn/twitter-bootstrap/2.1.1/bootstrap.js"=>
    "cdn/twitter-bootstrap/2.1.1/bootstrap-e632dd7f4540f1d3be0018f838aee23d.js",
   "cdn/twitter-bootstrap/2.1.1/bootstrap.min.js"=>
    "cdn/twitter-bootstrap/2.1.1/bootstrap.min-11b013daa39fe5eab17114289be1d003.js",
   "colors.js"=>"colors-6a8ca6d4c6fb9f92feb2fdd891e61c99.js",
   "datejs.js"=>"datejs-93b1753a31884c89b0201c68d56fdf1e.js",
   "jquery.colorpicker.js"=>
    "jquery.colorpicker-9e7ddffb282d406bf402d3d2d5254503.js",
   "jquery.miniColors.min.js"=>
    "jquery.miniColors.min-d1c382a2058e407b6350246cf51b4fb2.js",
   "jquery.resize.js"=>"jquery.resize-a12dbdaeeddfb89044682f657a7924ff.js",
   "jquery.ui.timepicker.js"=>
    "jquery.ui.timepicker-38d521691ad2ec8ce0947bfdca04aa1b.js",
   "jquery.weekcalendar.js"=>
    "jquery.weekcalendar-959ac000d128b83f47a4e84dc494f322.js",
   "mixable.js"=>"mixable-12f261b8fc519209f3adafe0bbee7f7e.js",
   "stripe_form.js"=>"stripe_form-0af48a0d7190f1e51b5a402d9ba7eb7f.js",
   "jquery-ui-1.8.18.custom.css"=>
    "jquery-ui-1.8.18.custom-7551d828d0bf37772e8415473f6c12ee.css",
   "jquery.colorpicker.css"=>
    "jquery.colorpicker-66632f9f1b70135e0e5705420e56a182.css",
   "jquery.miniColors.css"=>
    "jquery.miniColors-b3b4124c9df1f33352d8e959104f18d0.css",
   "jquery.weekcalendar.css"=>
    "jquery.weekcalendar-001188e50b8ec1f18d21eb3872efb6db.css",
   "fontawesome-webfont.eot"=>
    "fontawesome-webfont-34b23737d807477fbe093418411d5621.eot",
   "fontawesome-webfont.svg"=>
    "fontawesome-webfont-40b21f600944d1f9381b45dde616b433.svg",
   "fontawesome-webfont.ttf"=>
    "fontawesome-webfont-ab72f3c8de0d43ac899ca6ccbc943825.ttf",
   "fontawesome-webfont.woff"=>
    "fontawesome-webfont-1fb7cb2f1cf62a8c73dcc55c4685a755.woff",
   "glyphicons-halflings-white.png"=>
    "glyphicons-halflings-white-252e8593dee501cd4c5b7494e30ba515.png",
   "glyphicons-halflings.png"=>
    "glyphicons-halflings-1892260eba9f3b04199ff7c821e45a58.png",
   "bootstrap-affix.js"=>"bootstrap-affix-0ac1fd288beadf08990c4b885cf028ba.js",
   "bootstrap-alert.js"=>"bootstrap-alert-6f46aaea5b1b2e479c0c154779d64e5c.js",
   "bootstrap-button.js"=>
    "bootstrap-button-74d0c83dd09d45182fb4d6d893cc0e4b.js",
   "bootstrap-carousel.js"=>
    "bootstrap-carousel-d31d5bc0f7e21f69390b51a987c10c89.js",
   "bootstrap-collapse.js"=>
    "bootstrap-collapse-fae27de46a609e887f4eec484047eab5.js",
   "bootstrap-popover.js"=>
    "bootstrap-popover-044c7d2bfc69ecb0e9ee42a871da7af4.js",
   "bootstrap-scrollspy.js"=>
    "bootstrap-scrollspy-8a863c387dd7ae9042f2aa5efa9eb718.js",
   "bootstrap-tab.js"=>"bootstrap-tab-39962733b1f52a1c9d87de6dcccd7bc6.js",
   "bootstrap-tooltip.js"=>
    "bootstrap-tooltip-de45aad44981f5c0b4d4225e1279864e.js",
   "bootstrap-transition.js"=>
    "bootstrap-transition-691b5b04982ee1db04d6b4636dc9ed30.js",
   "bootstrap-typeahead.js"=>
    "bootstrap-typeahead-8f59eacbf7697908bd748808cc749f3e.js",
   "bootstrap.js"=>"bootstrap-41030769734cc80a22d31725d06c05b5.js",
   "coffee-script.js"=>"coffee-script-05b9725beadc560d7bde10f8ba20dcdc.js",
   "jquery-ui.js"=>"jquery-ui-debb1e9c34ad9d10a27a7d7cc59cf765.js",
   "jquery-ui.min.js"=>"jquery-ui.min-3fddf3dff321ce9a7bf01ae3671a3938.js",
   "jquery.js"=>"jquery-d2c56d55cdd2854c0eca501ab3c89719.js",
   "jquery.min.js"=>"jquery.min-d393cc3809f602097b297f537e8b63d8.js",
   "jquery_ujs.js"=>"jquery_ujs-7698b8d0e5a8c90934cd6b8eeaef8677.js",
   "jquery.iframe-transport.js"=>
    "jquery.iframe-transport-bad22e6014181b2e126cf092cb51c7bb.js",
   "jquery.remotipart.js"=>
    "jquery.remotipart-073936e44706ec64d8f38045e18e7ce0.js"}}
 => nil 
1.9.1 :003 > pp Rails.application.assets.each_logical_path.to_a; nil
["backgrounds/checkered.jpg",
 "bio/mm.jpg",
 "evergreen-logo-medium.png",
 "evergreen-logo.png",
 "icons/cvv.gif",
 "icons/envelope.png",
 "icons/glyphicons-halflings-white.png",
 "icons/glyphicons-halflings.png",
 "icons/gravatar.jpg",
 "icons/phone.png",
 "icons/skype-icon.png",
 "icons/twitter-icon.png",
 "application.js",
 "application.mobile.js",
 "controllers/admin/affiliates.js",
 "controllers/admin/application.js",
 "controllers/admin/appointments.js",
 "controllers/admin/businesses.js",
 "controllers/admin/calendar_settings_groups.js",
 "controllers/admin/calendars.js",
 "controllers/admin/calendars_main.js",
 "controllers/admin/calendars_mini_cal.js",
 "controllers/admin/clients.js",
 "controllers/admin/dashboards.js",
 "controllers/admin/locations.js",
 "controllers/admin/notifications.js",
 "controllers/admin/payments.js",
 "controllers/admin/personal_appointments.js",
 "controllers/admin/promotes.js",
 "controllers/admin/providers.js",
 "controllers/admin/registrations.js",
 "controllers/admin/scheduling_settings_groups.js",
 "controllers/admin/services.js",
 "controllers/admin/setup_steps.js",
 "controllers/admin/statics.js",
 "controllers/admin/styles_groups.js",
 "controllers/admin/users.js",
 "controllers/admin/work_appointments.js",
 "controllers/affiliates.js",
 "controllers/customer_center.js",
 "controllers/registrations.js",
 "controllers/sessions.js",
 "controllers/widget_appointments.js",
 "customer_center.js",
 "eg-widget.js",
 "minisite.js",
 "mobile.js",
 "safe.js",
 "setup_steps.js",
 "widget.js",
 "application.css",
 "bootstrap_and_overrides.css",
 "customer_center.css",
 "dashboard.css",
 "jquery-ui-override.css",
 "mobile.css",
 "setup_steps.css",
 "users.css",
 "widget-include.css",
 "widget.css",
 "utils.js",
 "colors.png",
 "images/ui-bg_diagonals-thick_90_eeeeee_40x40.png",
 "images/ui-bg_flat_15_cd0a0a_40x100.png",
 "images/ui-bg_glass_100_e4f1fb_1x400.png",
 "images/ui-bg_glass_50_3baae3_1x400.png",
 "images/ui-bg_glass_80_d7ebf9_1x400.png",
 "images/ui-bg_highlight-hard_100_f2f5f7_1x100.png",
 "images/ui-bg_highlight-hard_70_000000_1x100.png",
 "images/ui-bg_highlight-soft_100_deedf7_1x100.png",
 "images/ui-bg_highlight-soft_25_ffef8f_1x100.png",
 "images/ui-icons_2694e8_256x240.png",
 "images/ui-icons_2e83ff_256x240.png",
 "images/ui-icons_3d80b3_256x240.png",
 "images/ui-icons_72a7cf_256x240.png",
 "images/ui-icons_ffffff_256x240.png",
 "trigger.png",
 "bootbox.min.js",
 "bootstrap-dropdown.js",
 "bootstrap-modal.js",
 "calendars_main.js.backup",
 "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom.js",
 "cdn/jquery-ui/1.8.23/jquery-ui-1.8.24.custom.min.js",
 "cdn/jquery/1.8.1/jquery-1.8.1.js",
 "cdn/jquery/1.8.1/jquery-1.8.1.min.js",
 "cdn/twitter-bootstrap/2.1.1/bootstrap.js",
 "cdn/twitter-bootstrap/2.1.1/bootstrap.min.js",
 "colors.js",
 "datejs.js",
 "jquery.colorpicker.js",
 "jquery.miniColors.min.js",
 "jquery.resize.js",
 "jquery.ui.timepicker.js",
 "jquery.weekcalendar.js",
 "mixable.js",
 "stripe_form.js",
 "jquery-ui-1.8.18.custom.css",
 "jquery.colorpicker.css",
 "jquery.miniColors.css",
 "jquery.ui.timepicker.css",
 "jquery.weekcalendar.css",
 "jquery-ui.js",
 "jquery-ui.min.js",
 "jquery.js",
 "jquery.min.js",
 "jquery_ujs.js",
 "saas_admin.css",
 "jquery.iframe-transport.js",
 "jquery.remotipart.js"]
 => nil 
```

**Comment by manuelmeurer** [comment] 2012-10-15 14:26
I'm getting this error as well ("admin.css isn't precompiled"). It doesn't seem to happen immediately after deploy but after a while and a restart fixes it.

**Comment by ndbroadbent** [comment] 2012-10-16 18:48
Hi there, please let me know if updating to `0.1.16` solves your problem. We've fixed an issue where the `tmp:create` task was blowing away the cache

**Comment by manuelmeurer** [comment] 2012-10-17 17:54
Tried it, same error. To clarify: it doesn't happen immediately after precompiling, but a couple requests in.

**Comment by ndbroadbent** [comment] 2012-10-23 05:59
Sorry I haven't got back to you about this. It's very hard to debug something without being able to reproduce it. 
Are you deploying via capistrano? Are you using any gems that use or alter the behavior of assets?

@macmartine - It's strange that `Rails.application.config.assets` doesn't contain keys for `:digest_files` and `:source_digests`. This indicates that the gem is not loading properly, or is unable to override the sprockets config. Could you please post the contents of your Gemfile?

Thanks!

**Comment by ndbroadbent** [comment] 2012-10-25 10:05
I have made a few substantial changes recently. The most important one is that I've reverted `manifest.yml` to the original format and added a new `sources_manifest.yml` to keep track of source digests.
This should mean that the production environment is now identical to vanilla Rails `3.2.x`, and you should even be able to put the `turbo-sprockets-rails3` gem in the `:assets` group and have it turned off in production.
Please update to version `0.2.0` and let me know if that helps.

Thanks!

P.S. If you feel like giving up after this, please feel free to let me know and I'll just close this issue. I'm unable to reproduce it, and haven't received any other reports, so it might be an edge case related to your app.

**Comment by manuelmeurer** [comment] 2012-10-25 11:11
I'll try out the new version and report back. Thanks for your work on this!

**Comment by manuelmeurer** [comment] 2012-10-25 13:10
Now I'm getting this error on deploy:

```
 [myapp.com] sh -c 'cd /home/rails/myapp/releases/20121025130742 && bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile --trace'
 ** [out :: myapp.com] ** Invoke assets:precompile (first_time)
 ** [out :: myapp.com] ** Execute assets:precompile
 ** [out :: myapp.com] ** Invoke assets:precompile:all (first_time)
 ** [out :: myapp.com] ** Invoke assets:cache:clean (first_time)
 ** [out :: myapp.com] ** Invoke assets:environment (first_time)
 ** [out :: myapp.com] ** Execute assets:environment
 ** [out :: myapp.com] ** Invoke environment (first_time)
 ** [out :: myapp.com] ** Execute environment
 ** [out :: myapp.com] ** Execute assets:cache:clean
 ** [out :: myapp.com] ** Execute assets:precompile:all
 ** [out :: myapp.com] rake aborted!
 ** [out :: myapp.com] wrong number of arguments (2 for 1)
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/compass-rails-1.0.1/lib/compass-rails/patches/static_compiler.rb:7:in `write_manifest_with_sprites'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.0/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:71:in `compile'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.0/lib/turbo-sprockets/tasks/assets.rake:80:in `internal_precompile'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.0/lib/turbo-sprockets/tasks/assets.rake:87:in `block (3 levels) in <top (required)>'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
 ** [out :: myapp.com] /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.0/lib/turbo-sprockets/tasks/assets.rake:34:in `invoke_or_reboot_rake_task'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.0/lib/turbo-sprockets/tasks/assets.rake:40:in `block (2 levels) in <top (required)>'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
 ** [out :: myapp.com] /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'
 ** [out :: myapp.com] /home/rails/myapp/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
 ** [out :: myapp.com] Tasks: TOP => assets:precompile:all
```

**Comment by manuelmeurer** [comment] 2012-10-25 13:23
Hmm, this seems to be a unrelated error. `compass-rails` mokeypatches Sprockets::StaticCompiler, just like `turbo-sprockets-rails3`, and they don't play well together... shall I open a separate issue for this?

EDIT: I also tested the latest version of `compass-rails` (v1.0.3), same issue.

**Comment by ndbroadbent** [comment] 2012-10-25 21:11
YES! Problem solved! I've changed my code so that I'm no longer touching the `write_manifest` method (now using a separate `write_sources_manifest` method), so `compass-rails` should now be fully compatible. Please update to `0.2.1` and let me know if that solves all your problems! Nothing like a monkey-patch fight to keep you wondering WTH is going on...

@macmartine - Your problem should now also be solved, especially since I've reverted the manifest format.

Thanks so much for helping me to get to the bottom of this!

**Closed as completed by ndbroadbent** 2012-10-25 21:11 UTC

**Comment by manuelmeurer** [comment] 2012-10-25 22:10
v0.2.1 works fine so far, no errors on deploy and no `... isn't precompiled`. Seems like you nailed it. Good work! :)

**Comment by ndbroadbent** [comment] 2012-10-25 22:11
Awesome, glad to hear! Thanks again for your help :)

**Comment by macmartine** [comment] 2012-10-26 20:46
Now my mailers that are run by resque fail with errors like: eg-logo.png isn't precompiled

**Comment by ndbroadbent** [comment] 2012-10-26 20:51
ok, I've opened a new issue for that at; https://github.com/ndbroadbent/turbo-sprockets-rails3/issues/23

**Comment by ndbroadbent** [comment] 2012-10-26 21:17
@macmartine - Please try updating and restarting your resque workers first.

Second, try adding the `turbo-sprockets-rails3` gem to the `:assets` group. If it's still failing, please run `RAILS_ENV=production rails console` and post the output of the following command in over at https://github.com/ndbroadbent/turbo-sprockets-rails3/issues/23

```
pp Rails.application.config.assets; nil
```

Please also let me know how you are including `eg-logo.png` in your mailer. Is it an image tag, or in CSS?

Cheers

**Comment by ndbroadbent** [comment] 2012-10-26 21:18
I've run into asset problems myself when I forgot to update the workers, so that's where I would begin to look :)
